### ISSUE TITLE
Want Code

### ISSUE THREAD

**Issue by iezhuozhuo** [zhanghainan/ReCoSa#1]
您好！看了你的论文 ReCoSa: Detecting the Relevant Contexts with Self-Attention for
Multi-turn Dialogue Generation，就直接过来了想看看您的源码，不知道什么时候可以release？

**Comment by zhanghainan** [comment]
大概下周吧，最近一直在忙别的事情，耽搁了~

**Comment by YufanPaPa** [comment]
您好，请问论文中用到的京东对话数据集有什么方式获取呢，目前京东官方已经不提供下载了
