### ISSUE TITLE
和transformer的差别

### ISSUE THREAD

**Issue by DericZhao** [zhanghainan/ReCoSa#10]
首先感谢作者公开的源码
源代码中是使用tensorflow写的，但是我对tensorflow并不熟悉
请问作者 我是否可以 使用pytorch的transformer 在最前面加一层lstm encoder层
万分感谢

**Comment by mjw1997** [comment]
谢谢作者公开源码，仔细拜读了您的论文，近段时间复现了代码。
论文中提到的训练集的困惑度PPL，在代码文件夹中没有找到体现。
本人也试图使用各种方法求loss值，然后做exp（)操作，得到PPL都特别大，达到10,000多。
请教一下您，论文里测试的PPL如何求出。恳求您回复~

**Comment by zhanghainan** [comment]
> 首先感谢作者公开的源码
> 源代码中是使用tensorflow写的，但是我对tensorflow并不熟悉
> 请问作者 我是否可以 使用pytorch的transformer 在最前面加一层lstm encoder层
> 万分感谢

可以的，你自己加一层LSTM的encoder就行
