### ISSUE TITLE
能公开一下处理Ubuntu数据的代码吗？

### ISSUE THREAD

**Issue by Sry2016** [zhanghainan/ReCoSa#12]

**Comment by zhanghainan** [comment]
那个代码已经太久了，我已经找到不到了。。。就是按照轮数切分就可以了，例如A1B1A2B2A3B3，可以处理为A1B1,A1B1A2B2,A1B1A2B2A3B3三份。预处理代码就用官网的就可以了。

**Comment by Sry2016** [comment]
好的，谢谢。还有一个问题，论文里提到说每一句最大的长度是50。这一步我在官网上的预处理代码里好像没看到，是不是自己处理的？另外，train/valid/test 得到了 3,980,000, 10,000 and 10,000这么多是 按照你这么划分完之后得到的，还是划分之前的有这么多。（"A1B1A2B2A3B3"有3,980,000还是“A1B1,A1B1A2B2,A1B1A2B2A3B3”这样的有3,980,000）

**Comment by zhanghainan** [comment]
划分完以后自己处理长度，其次这个数据是划分以后切成这个比例的。

**Comment by Sry2016** [comment]
感谢，祝好！

**Comment by Sry2016** [comment]
你好，又有一个问题。您是怎么把ubuntu的单词词表搞到15000这么大的。

**Comment by Sry2016** [comment]
- source: what shall we do after the volleyball match ?  </d>  how about going to the Olympic souvenir store to have a look ? I remember there is one in the gym .  </d>  that's a good idea . I was thinking of buying some gifts for my family .  </d>  me , too . What did you have in mind ?  </d>  I haven't decided yet , but I think the Olympic Mascots are a must .  </d>  I agree . They're very lovely , especially " Huan Huan " .  </d>  is that the red one ? That is my favorite , too . Do you know how much they are ?  </d>  the five dolls are sold together as a set , and they're priced according to the size . The bigger they are the more expensive .  </d>  oh , I see . If I buy more than a set , can I get any discount ?  </d>  I don't think so . All the souvenirs of the Olympic Games are very hot right now .
- expected: any other ideas ?
- got: 

- source: what shall we do after the volleyball match ?  </d>  how about going to the Olympic souvenir store to have a look ? I remember there is one in the gym .  </d>  that's a good idea . I was thinking of buying some gifts for my family .  </d>  me , too . What did you have in mind ?  </d>  I haven't decided yet , but I think the Olympic Mascots are a must .  </d>  I agree . They're very lovely , especially " Huan Huan " .  </d>  is that the red one ? That is my favorite , too . Do you know how much they are ?  </d>  the five dolls are sold together as a set , and they're priced according to the size . The bigger they are the more expensive .  </d>  oh , I see . If I buy more than a set , can I get any discount ?  </d>  I don't think so . All the souvenirs of the Olympic Games are very hot right now .  </d>  any other ideas ?
- expected: there are lots of things , such as postcards , key chains , posters and various arts and crafts .
- got: 
为什么我复现出来都是这样的，got是空的、好奇怪，

**Comment by Sry2016** [comment]
打印了pred出来全都是3333，也就是</s>

**Comment by zhanghainan** [comment]
这个你需要自己调试一下输入的内容是否正确，不是我的代码问题。
其次英文词表15000已经很少了，整个数据集统计下来应该是好几万的词表大小。

**Comment by Sry2016** [comment]
谢谢，我好想在一个已经关闭的问题里找到了同样的情况。
source:
Hey man , you wanna buy some weed ?  </d>  Some what ? 
Hey man , you wanna buy some weed ?  </d>  Some what ?  </d>  Weed ! You know ? Pot , Ganja , Mary Jane some chronic ! 
target:
 Weed ! You know ? Pot , Ganja , Mary Jane some chronic ! 
 Oh , umm , no thanks . 

这样处理数据好像是没有问题，我理解target里那个</d>好像加不加没有影响。
ubuntu那个好奇怪，我处理完之后看起来数据非常脏。。词表有20多万。
如果可以的话，您方便提供给我你使用的ubuntu数据集吗？看微软的一篇文章里说和你们使用的一样的数据集。

**Comment by Sry2016** [comment]
谢谢，我好想在一个已经关闭的问题里找到了同样的情况。
source:
Hey man , you wanna buy some weed ?"</d>" Some what ?
Hey man , you wanna buy some weed ?</d>" Some what ? Weed ! You know ?</d>" Pot , Ganja , Mary Jane some chronic !
target:
Weed ! You know ? Pot , Ganja , Mary Jane some chronic !
Oh , umm , no thanks .

这样处理数据好像是没有问题，我理解target里"</d>"那个好像加不加没有影响。
ubuntu那个好奇怪，我处理完之后看起来数据非常脏。。词表有20多万。
如果可以的话，您方便提供给我你使用的ubuntu数据集吗？看微软的一篇文章里说和你们使用的一样的数据集。

**Comment by zhanghainan** [comment]
Ubuntu直接去官网下载就可以了
如果出不来结果，可以试试小一点的数据集多跑跑

**Comment by Sry2016** [comment]
分隔符打不出来我也不知道为什么...
ubuntu我处理完的数据很脏，方便的话还是想要一下您的数据。
我多跑几轮试试，多谢。

**Comment by zhanghainan** [comment]
我真的找不到这个数据了。。。我就是按照官网的script处理的。。。

**Comment by Sry2016** [comment]
。。。。。我也是，但是我用你们的程序处理完词表有好几十万。。。是不是要再额外清洗一下。。

**Comment by zhanghainan** [comment]
选择按照词频最高的15000留下来做词表
