### ISSUE TITLE
how to obtain the jd dataset

### ISSUE THREAD

**Issue by YufanPaPa** [zhanghainan/ReCoSa#2]
您好，请问论文中用到的京东对话数据集有什么方式获取呢，目前京东官方已经不提供下载了

**Comment by Ailing-Zou** [comment]
同问呐~~

**Comment by zhanghainan** [comment]
http://jddc.jd.com/process 这个比赛好像已经关了，可以明年报名参赛。现在可以给官网发邮件，申请试试
