### ISSUE TITLE
上下文输入

### ISSUE THREAD

**Issue by lost-person** [zhanghainan/ReCoSa#6]
你好！十分感谢你的开源代码。只是在阅读时，有一处细节不太了解——在模型输入时，你将多轮的上下文拆解成多个样本。即，

The dialogue data：Hello How are you? Good, you? I'm fine, what's new?
Souce looks like:

Hello How are you? </d>

Hello How are you? </d> Good, you? </d>

Hello How are you? </d> Good, you? </d> I'm fine, what's new?</d>

Target:

Good, you?</d>

I'm fine, what's new?</d>

Nothing much...</d>

请问，这是多轮对话的通用处理方式吗？还是直接将多轮的上下文作为输入，也可以？

可能这个问题略显幼稚，但还是期待你的回复。

**Comment by zhanghainan** [comment]
为了扩大数据量，一般都是做拆分处理。因为设计多轮对话机器人，不可能只需要回答最后一句话，这显然是不合理的。为了让机器能够更多的学习，所以做了这种操作
